services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=petshop
      - MYSQL_PORT=3306
    ports:
      - '8080:8080'
    volumes:
      - .:/app
  mysql:
    image: mysql:8.2.0
    ports:
      - '3306:3306'
    command:
      - --default-authentication-plugin=caching_sha2_password
    restart: always
    volumes:
      - ./docker/mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: petshop
